language: node_js
node_js:
  - "0.10"
before_install:
  - time sudo pip install --use-mirrors -r test-infra/requirements.txt
  - rvm use 1.9.3 --fuzzy
  - if [ "$TWBS_TEST" = validate-html ]; then echo "ruby=$(basename $(rvm gemdir)) jekyll=$JEKYLL_VERSION" > pseudo_Gemfile.lock; fi
install:
  - time npm install -g grunt-cli
  - time ./test-infra/s3_cache.py download 'npm packages' test-infra/npm-shrinkwrap.canonical.json ./node_modules || time ./test-infra/uncached-npm-install.sh
  - if [ "$TWBS_TEST" = validate-html ]; then time ./test-infra/s3_cache.py download rubygems pseudo_Gemfile.lock $(rvm gemdir) || gem install -N jekyll -v $JEKYLL_VERSION; fi
after_script:
  - if [ "$TWBS_TEST" = core ]; then time ./test-infra/s3_cache.py upload 'npm packages' test-infra/npm-shrinkwrap.canonical.json ./node_modules; fi
  - if [ "$TWBS_TEST" = validate-html ]; then time ./test-infra/s3_cache.py upload rubygems pseudo_Gemfile.lock $(rvm gemdir); fi
env:
  global:
    - JEKYLL_VERSION: 1.4.1
    - SAUCE_USERNAME: bootstrap
    - secure: "B1VGQ+65cNzvENxHSf4R5tHtjCb0FkdOyAYr3VNMMZBLXuLKu4501bPrXqHDlo0xyZfuLiUxu6DloTCa5FgGde9EpuuzMz5RSiH6g4mg9t+kayIpTO1rITFb4yQYsfRlXnDaJy1HafYQ5+Lfs1rNxeQuSYltvHvIZ4nRs9JOCc0="
    - secure: "LzktwWC9OrvnDjVQiGyWU06aCRMOL25wxnj9PP6JzBWRCjONNwKxbOBe4nlBUjJMWxaa6UViYmYIk7LqNGE5iiFESFaibrz/GoT/lbYlSfsePFbeGi4NYOvbkJJ0D3k45WEZmbrF/Wz4WjE4lowYrRm7YnEj3AJwXAuWk3jDiQU="
  matrix:
    - TWBS_TEST=browserstack-js-unit
matrix:
  fast_finish: true
